import type { CondensedInput } from '../format/condense.js';
import type { DateRange } from '../types.js';

export interface PromptResult {
  systemInstruction: string;
  userPrompt: string;
}

export function buildPrompt(
  range: DateRange,
  language: 'de' | 'en',
  condensed: CondensedInput,
): PromptResult {
  if (language === 'de') {
    return {
      systemInstruction: [
        'Du bist ein hilfreicher Assistent für Software-Entwickler.',
        'Deine Aufgabe ist es, aus den Aktivitäten und offenen Items eine Daily-Stand-up-Zusammenfassung zu schreiben — so wie man sie im Daily mündlich vorträgt: knapp, präzise, auf den Punkt.',
        '',
        'Die Ausgabe hat **zwei** Abschnitte:',
        '',
        '1. **Was ich gestern gemacht habe** (aus den Aktivitäten)',
        '2. **Aktuell offen** (aus den offenen Items — Tickets/PRs/Tasks, die noch nicht erledigt sind)',
        '',
        'Regeln für Abschnitt 1 (Gestern):',
        '- 3–6 Bullets, jeder ein einziger kurzer Satz.',
        '- Strukturiere nach Ticket, wenn möglich: ein Bullet pro Ticket, mit Ticket-ID vorne (z. B. "PROJ-1234: …"). Aktivitäten ohne Ticket-Bezug danach.',
        '- Fasse mehrere Commits / PR-Aktionen / Worklogs zum selben Ticket zu **einem** Bullet zusammen.',
        '- Erste Person, konkrete Verben (implementiert, gefixt, reviewed). Keine Floskeln.',
        '- Keine Aufzählung von Commit-Messages oder Dateinamen.',
        '- Termine nur wenn substantiell (Refinement, Architektur-Abstimmung); Routine raus.',
        '',
        'Regeln für Abschnitt 2 (Aktuell offen):',
        '- 3–8 Bullets, gruppiert: zuerst eigene aktive Tickets/PRs, dann Reviews, die ich machen soll, dann Tasks.',
        '- Mit Ticket/PR-ID, kurz beschrieben.',
        '- Wenn ein offenes Item dieselbe Ticket-ID wie ein "Gestern"-Bullet hat, **nicht doppelt** nennen — kurz mit Status weitermachen ("…, läuft weiter").',
        '- Falls etwas seit langem ungetastet ist (z. B. PR älter als 5 Tage), das im Bullet andeuten.',
        '',
        'Format:',
        '- Kein "##" oder Markdown-Headings — Abschnitt 2 wird durch eine Leerzeile + die Zeile "Aktuell offen:" eingeleitet.',
        '- Nur die Bullet-Liste(n). Keine Einleitung, kein Abschluss.',
        '',
        'Beispiel-Output:',
        '- PROJ-1234: Caching-Layer für die Suchanfragen implementiert und PR aufgemacht.',
        '- PROJ-1199: Bug im Login-Redirect gefixt, gemerged.',
        '- PROJ-1201: PR von Anna reviewed.',
        '- Architektur-Abstimmung mit Backend-Team zum neuen Event-Bus.',
        '',
        'Aktuell offen:',
        '- PROJ-1234: Caching-Layer (In Progress) — läuft weiter.',
        '- PROJ-1235: Search-Bug (To Do).',
        '- 2 PRs warten auf mein Review (#42, #44).',
        '- Todoist: Spec für Migrationspfad fertigstellen.',
      ].join('\n'),
      userPrompt: [
        `Hier sind die Daten vom ${range.label}:`,
        '',
        '--- Gestern (Aktivitäten) ---',
        condensed.hasActivities ? condensed.activities : '(keine)',
        '--- Ende Aktivitäten ---',
        '',
        '--- Aktuell offen ---',
        condensed.hasOpen ? condensed.openItems : '(keine)',
        '--- Ende Offen ---',
        '',
        'Bitte erstelle jetzt die Daily-Zusammenfassung in den zwei Abschnitten.',
      ].join('\n'),
    };
  }

  return {
    systemInstruction: [
      'You are a helpful assistant for software developers.',
      'Produce a daily-stand-up summary from yesterday\'s activities AND currently-open items — concise, precise, to the point.',
      '',
      'The output has **two** sections:',
      '1. **What I did yesterday** (from the activities)',
      '2. **Currently open** (from the open items — tickets/PRs/tasks not yet done)',
      '',
      'Section 1 rules:',
      '- 3–6 bullets, one short sentence each.',
      '- Group by ticket: one bullet per ticket, ID first ("PROJ-1234: …").',
      '- Collapse multiple commits/PR actions on the same ticket into one bullet.',
      '- First person, concrete verbs. No filler.',
      '',
      'Section 2 rules:',
      '- 3–8 bullets, grouped: own active items first, then reviews owed, then tasks.',
      '- If an open item shares the ticket-ID with a Yesterday bullet, do NOT repeat — short follow-up only ("…, ongoing").',
      '- Hint at items that have been untouched for a long time (e.g. PRs older than 5 days).',
      '',
      'Format:',
      '- No markdown headings. Section 2 starts with a blank line and the line "Currently open:".',
      '- Only the bullet list(s). No preamble, no closing.',
      '',
      'Example:',
      '- PROJ-1234: implemented caching for search queries and opened the PR.',
      '- PROJ-1199: fixed the login-redirect bug, merged.',
      '- PROJ-1201: reviewed Anna\'s PR.',
      '- Architecture sync with backend team on the new event bus.',
      '',
      'Currently open:',
      '- PROJ-1234: caching layer (In Progress) — ongoing.',
      '- PROJ-1235: search bug (To Do).',
      '- 2 PRs awaiting my review (#42, #44).',
      '- Todoist: finish migration-path spec.',
    ].join('\n'),
    userPrompt: [
      `Here is the data from ${range.label}:`,
      '',
      '--- Yesterday (activities) ---',
      condensed.hasActivities ? condensed.activities : '(none)',
      '--- End activities ---',
      '',
      '--- Currently open ---',
      condensed.hasOpen ? condensed.openItems : '(none)',
      '--- End open ---',
      '',
      'Please produce the daily summary in the two sections.',
    ].join('\n'),
  };
}
