import type { CondensedInput } from '../format/condense.js';
import type { DateRange } from '../types.js';

export interface PromptResult {
  systemInstruction: string;
  userPrompt: string;
}

export function buildPrompt(
  range: DateRange,
  language: 'de' | 'en',
  condensed: CondensedInput,
  today: boolean = false,
): PromptResult {
  if (language === 'de') {
    const doneLabel = today ? 'Heute (bereits erledigt)' : 'Gestern';
    const planLabel = today ? 'Noch heute' : 'Heute';
    const dataIntro = today
      ? `Hier sind deine Daten von heute (${range.label}):`
      : `Hier sind die Daten vom ${range.label}:`;
    return {
      systemInstruction: [
        'Du bist ein hilfreicher Assistent für Software-Entwickler.',
        'Deine Aufgabe ist es, aus drei Inputs eine Daily-Stand-up-Zusammenfassung zu schreiben — knapp, präzise, sprechbar.',
        '',
        'Du bekommst:',
        `1. **Aktivitäten** ${today ? 'von heute (was schon getan wurde)' : 'vom Vortag'} (Commits, Tickets, PRs, Termine, Mails — was getan wurde)`,
        '2. **Offene Items** (Tickets/PRs/Tasks, die noch nicht erledigt sind — zeitlos)',
        `3. **${today ? 'Restlicher Tageskalender' : 'Heutiger Kalender'}** (Termine, die ${today ? 'heute noch' : 'heute'} anstehen)`,
        '4. **Vorschläge** (nur wenn aktuell nichts in Bearbeitung — Pickup-Kandidaten aus dem Backlog)',
        '',
        `WICHTIG: Die Ausgabe MUSS IMMER aus zwei Abschnitten bestehen: "${doneLabel}" und "${planLabel}".`,
        `Der Abschnitt "${planLabel}" MUSS auch dann vorhanden sein, wenn keine Termine anstehen (dann werden nur offene Arbeiten gelistet).`,
        '',
        `Regeln "${doneLabel}":`,
        '- 3–6 Bullets, jeder ein einziger kurzer Satz.',
        '- Strukturiere nach Ticket: ein Bullet pro Ticket, mit Ticket-ID vorne ("PROJ-1234: …").',
        '- Mehrere Commits / PR-Aktionen / Worklogs zum selben Ticket → ein Bullet.',
        '- Erste Person, konkrete Verben (implementiert, gefixt, reviewed). Keine Floskeln.',
        '- WICHTIG: Wenn ein Ticket eine "Resolution" (Lösungsweg) hat (z. B. "Zurückgestellt", "Abgebrochen", "Duplikat"), MUSS dies im Bullet-Point erwähnt werden.',
        '',
        'Prozess-Kontext für deine Zusammenfassungen:',
        '- Branches → Deployment-Stages in dieser Firma:',
        '  - feature/* deployt auf TST (eigene Feature-Route)',
        '  - develop deployt auf TST (Sammelroute)',
        '  - master deployt auf ABN (und nach Jenkins-Promotion auf PROD)',
        '- Merge feature/* → develop: NICHT als "implementiert" formulieren — die Implementierung lief schon vorher auf dem Feature-Branch. Formuliere als "auf der dev-Route in TST verfügbar" oder "in develop integriert für TST-Sammeltest".',
        '- Merge develop → master: NICHT als "gelöst/fertig" formulieren — formuliere als "auf ABN gebracht" oder "wartet auf Abnahme".',
        '- Wenn nur ein develop→master-Merge passiert ist (kein Feature-PR im selben Range): NIE "Ticket umgesetzt" sagen — es ist eine reine Stage-Promotion.',
        '- Jira-Status-Mapping (unabhängig von Branches):',
        '  - "In Prüfung" → "Kann jetzt getestet werden" oder "Bereit zum Test".',
        '  - "Gelöst" → "Ist jetzt in Abnahme" oder "Wartet auf finale Abnahme".',
        '  - "Geschlossen" → final abgenommen, ggf. auf PROD.',
        '',
        `Regeln "${planLabel}":`,
        '- 3–6 Bullets. Reihenfolge: laufende eigene Arbeit (offene Tickets/PRs), dann Reviews die ich machen soll, dann Termine, dann Tasks.',
        `- Wenn ein offenes Item dieselbe Ticket-ID wie ein "${doneLabel}"-Bullet hat → kurz "läuft weiter" o. ä., nicht doppelt erklären.`,
        '- Termine kompakt: "14:00 Architektur-Sync mit Backend".',
        '- Wenn der Vorschläge-Block befüllt ist (nichts läuft aktuell), 1–2 konkrete Vorschläge als "könnte heute … angehen" formulieren — mit Ticket-ID.',
        '',
        'Format:',
        `- Kein Markdown-Heading. "${planLabel}" wird durch eine Leerzeile + Zeile "${planLabel}:" eingeleitet.`,
        '- Nur die Bullet-Listen. Keine Einleitung, kein Abschluss.',
        '',
        'Beispiel-Output:',
        '- PROJ-1234: Caching-Layer implementiert, Ticket ist bereit zum Test (In Prüfung).',
        '- PROJ-1199: Login-Redirect-Fix von develop nach master gemerged — Ticket ist jetzt auf ABN.',
        '- PROJ-1201: PR von Anna reviewed.',
        '',
        `${planLabel}:`,
        '- PROJ-1234: Caching-Layer (In Progress) — läuft weiter.',
        '- 2 PRs warten auf mein Review (#42, #44).',
        '- 14:00 Refinement, 15:30 Architektur-Sync.',
      ].join('\n'),
      userPrompt: [
        dataIntro,
        '',
        `--- ${doneLabel} (Aktivitäten) ---`,
        condensed.hasActivities ? condensed.activities : '(keine)',
        '--- Ende Aktivitäten ---',
        '',
        '--- Offene Items ---',
        condensed.hasOpen ? condensed.openItems : '(keine)',
        '--- Ende Offen ---',
        '',
        '--- Vorschläge (Pickup-Kandidaten, falls nichts läuft) ---',
        condensed.hasSuggestions ? condensed.suggestions : '(keine)',
        '--- Ende Vorschläge ---',
        '',
        `--- ${today ? 'Restlicher Tageskalender' : 'Heutiger Kalender'} ---`,
        condensed.hasAgenda ? condensed.agenda : '(keine)',
        '--- Ende Kalender ---',
        '',
        'Bitte erstelle jetzt die zweigeteilte Daily-Zusammenfassung.',
      ].join('\n'),
    };
  }

  const doneLabelEn = today ? 'Today (already done)' : 'Yesterday';
  const planLabelEn = today ? 'Rest of today' : 'Today';
  const dataIntroEn = today
    ? `Here is your data from today (${range.label}):`
    : `Here is the data from ${range.label}:`;

  return {
    systemInstruction: [
      'You are a helpful assistant for software developers.',
      'Produce a daily-stand-up summary from three inputs — concise, precise, to the point.',
      '',
      'You get:',
      `1. **${today ? "Today's activities (already done)" : "Yesterday's activities"}** (commits, tickets, PRs, meetings, mail — what was done)`,
      '2. **Open items** (tickets/PRs/tasks not yet done — timeless)',
      `3. **${today ? 'Rest-of-day calendar' : "Today's calendar"}** (meetings still upcoming today)`,
      '4. **Suggestions** (only when nothing is currently in progress — pickup candidates from the backlog)',
      '',
      `Output has **two** sections: "${doneLabelEn}" and "${planLabelEn}". "${planLabelEn}" merges open work + upcoming meetings into one speakable block.`,
      '',
      `${doneLabelEn} rules:`,
      '- 3–6 bullets, one short sentence each.',
      '- Group by ticket: one bullet per ticket, ID first.',
      '- Collapse same-ticket activities into one bullet.',
      '- First person, concrete verbs.',
      '',
      'Branch/stage context: branch merges are stage promotions, not implementation events.',
      '- feature/* → develop: NOT "implemented" — code was already running on the feature branch; phrase as "available on dev route in TST".',
      '- develop → master: NOT "resolved/done" — phrase as "promoted to ABN" / "awaiting acceptance".',
      '',
      `${planLabelEn} rules:`,
      '- 3–6 bullets. Order: own ongoing work, then reviews owed, then meetings, then tasks.',
      `- If an open item shares ticket-ID with a "${doneLabelEn}" bullet → short follow-up ("ongoing"), no full re-explain.`,
      '- Compact meeting format: "14:00 Architecture sync with backend".',
      '- If the suggestions block is populated (nothing currently in progress), surface 1–2 concrete picks as "could tackle … today" — with ticket ID.',
      '',
      'Format:',
      `- No markdown headings. "${planLabelEn}" starts with a blank line and "${planLabelEn}:".`,
      '- Only the bullet lists.',
      '',
      'Example:',
      '- PROJ-1234: implemented caching for search queries and opened the PR.',
      '- PROJ-1199: fixed login-redirect bug, merged.',
      '- PROJ-1201: reviewed Anna\'s PR.',
      '- Architecture sync with backend team on the new event bus.',
      '',
      `${planLabelEn}:`,
      '- PROJ-1234: caching layer (In Progress) — ongoing.',
      '- 2 PRs awaiting my review (#42, #44).',
      '- 14:00 refinement, 15:30 architecture sync.',
      '- Todoist: finish migration-path spec (due tomorrow).',
    ].join('\n'),
    userPrompt: [
      dataIntroEn,
      '',
      `--- ${doneLabelEn} (activities) ---`,
      condensed.hasActivities ? condensed.activities : '(none)',
      '--- End activities ---',
      '',
      '--- Open items ---',
      condensed.hasOpen ? condensed.openItems : '(none)',
      '--- End open ---',
      '',
      '--- Suggestions (pickup candidates if nothing in progress) ---',
      condensed.hasSuggestions ? condensed.suggestions : '(none)',
      '--- End suggestions ---',
      '',
      `--- ${today ? 'Rest-of-day calendar' : "Today's calendar"} ---`,
      condensed.hasAgenda ? condensed.agenda : '(none)',
      '--- End calendar ---',
      '',
      'Please produce the two-section daily summary.',
    ].join('\n'),
  };
}
